package helfi2012.chat.tcpconnection

object JSONKeys {
    /* USER */
    val JSON_KEY_USER_LIST = "USER_OBJECT"
    val JSON_KEY_USER_LOGIN = "USER_LOGIN"
    val JSON_KEY_USER_PASSWORD = "USER_PASSWORD"
    val JSON_KEY_USER_IP_ADDRESS = "USER_IP_ADDRESS"
    val JSON_KEY_USER_ONLINE = "USER_ONLINE"
    /* DIALOG */
    val JSON_KEY_DIALOG_LIST = "DIALOG_LIST"
    val JSON_KEY_START_INDEX = "START_INDEX"
    val JSON_KEY_COUNT = "COUNT"
    /* CHAT_MESSAGE */
    val JSON_KEY_MESSAGE_LIST = "MESSAGE_LIST"
    val JSON_KEY_MESSAGE_NAME = "MESSAGE_NAME"
    val JSON_KEY_MESSAGE_TEXT = "MESSAGE_TEXT"
    val JSON_KEY_MESSAGE_TIME = "MESSAGE_TIME"
    /* ATTACHMENTS */
    val JSON_KEY_MESSAGE_ATTACHMENTS = "MESSAGE_ATTACHMENTS"
    val JSON_KEY_ATTACHMENT_NAME = "ATTACHMENT_NAME"
    val JSON_KEY_ATTACHMENT_PROGRESS = "ATTACHMENT_PROGRESS"
    val JSON_KEY_ATTACHMENT_LENGTH = "ATTACHMENT_LENGTH"
    val JSON_KEY_ATTACHMENT_RATIO = "ATTACHMENT_RATIO"
    /* MAIN */
    val JSON_KEY_RESPONSE_TYPE = "RESPONSE_TYPE"
    /* EXTRA */
    val JSON_KEY_COMPANION_LOGIN = "COMPANION_LOGIN"
    val JSON_KEY_VALUE1 = "VALUE1"
    val JSON_KEY_VALUE2 = "VALUE2"
    val JSON_KEY_VALUE3 = "VALUE3"
    val JSON_KEY_VALUE4 = "VALUE4"
    val JSON_KEY_VALUE5 = "VALUE5"
    val JSON_KEY_VALUE6 = "VALUE6"
    val JSON_KEY_VALUE7 = "VALUE7"
}
